config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :posts
  resources :users, only: :show

  get '/posts/category/:category', to: 'posts#category', as: 'category_posts'

  namespace :mypage do
    resources :posts, only: %i[index show destroy]
    resources :users, only: %i[show update]
    resources :bookmarks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  has_many :posts

  validates :name, presence: true, uniqueness: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :bookmark, optional: true
  has_many_attached :photos, dependent: :destroy

  validates :title, :description, :location, :category, presence: true
  validates :title, uniqueness: true, length: { maximum: 30 }
  validates :description, length: { minimum: 10 }

  include PgSearch::Model
  pg_search_scope :global_search, against: [:title], using: { tsearch: { prefix: true } }

  CATEGORIES = ["学校", "仕事", "生活", "手続き", "言語", "住居", "食", "気候", "その他"]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :bookmarks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/mypage/bookmarks_controller.rb
class Mypage::BookmarksController < ApplicationController
  def index
    @user = current_user
    @bookmarks = Bookmark.all
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.user = current_user
    if @bookmark.save
      render json: { success: true }
    else
      render json: { success: false, errors: @bookmark.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def show
    @bookmark = Bookmark.find(params[:id])
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:name)
  end
end

app/controllers/mypage/posts_controller.rb
class Mypage::PostsController < ApplicationController
  def index
    @user = current_user
    @posts = @user.posts.all.order(created_at: :desc)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to mypage_posts_path, notice: "Post deleted successfully"
  end

  def show
    @post = Post.find(params[:id])
  end
end

app/controllers/mypage/users_controller.rb
class Mypage::UsersController < ApplicationController
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to mypage_user_path(@user), notice: "Post updated successfully"
    else
      puts @user.errors.full_messages
      render :show, status: :unprocessable_entity
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :location, :description, :avatar)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @posts = Post.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts =
      if params[:q].present?
        Post.global_search(params[:q]).order(created_at: :desc)
      else
        @posts = Post.all.order(created_at: :desc)
      end
  end

  def category
    @category = params[:category]
    @posts = Post.where(category: @category)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to post_path(@post)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  private

  def post_params
    params.require(:post).permit(:title, :description, :location, :category, photos: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @post = Post.find(params[:id])
    @user = @post.user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GlobeTales</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <div>
      <%= render "shared/navbar" %>
      <%= render "shared/flashes" %>
      <div class="page-body">
        <%= yield %>
      </div>
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/mypage/bookmarks/_bookmark_cards.html.erb
<div class="bookmark-cards">
  <% @bookmarks.each do | bookmark | %>
    <%= link_to mypage_bookmark_path(bookmark), class: "text-decoration-none" do  %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1579546929518-9e396f3cc809?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2940&q=80)">
        <h3><%= bookmark.name %></h3>
      </div>
    <% end %>
  <% end %>
</div>

app/views/mypage/bookmarks/_posts.html.erb
<div class="cards">
  <% @bookmark.posts.each do |post| %>
    <%= link_to post_path(post), class:"text-decoration-none text-black" do %>
      <div class="card-post">
        <% if post.photos.attached? %>
          <img src="<%= cl_image_path(post.photos.first.key)%>", class="first-img" >
        <% else %>
          <img src="<%= "https://source.unsplash.com/random/?#{post.title}" %>", class="first-img">
        <% end %>
        <div class="card-post-info">
          <h3 class="mb-2"><%= post.title %></h3>
          <div class="category-label">
            <div class="user-info">
              <%= image_tag post.user.avatar, class:"avatar-post me-2" %>
              <p><%= post.user.name %></p>
            </div>
            <p class="label"><%= post.category %></p>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/mypage/bookmarks/index.html.erb
<div class="container my-4">
  <h3 class="text-center mb-4">お気に入り一覧 🧡</h3>
  <!-- Button trigger modal -->
  <button type="button" class="btn btn-warning mb-2 float-end new-btn" data-bs-toggle="modal" data-bs-target="#exampleModal">
    カテゴリーを追加
  </button>
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">カテゴリーを追加</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <%= simple_form_for(@bookmark) do |f| %>
            <%= f.input :name, label:"タイトル", input_html:{class:'form-control bg-white'} %>
            <div class="text-center">
              <%= f.submit "保存", class: "btn btn-info text-white col-4" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <%= render "bookmark_cards" %>
</div>

app/views/mypage/bookmarks/show.html.erb
<div class="container my-4">
  <h3 class="text-center mb-4"><%= @bookmark.name %></h3>
  <%= render "posts" %>
</div>

app/views/mypage/posts/_postcard.html.erb
<div class="cards">
  <% @posts.each do |post| %>
    <div id="delete-item-wrapper">
      <div id="delete-item">
        <%= link_to mypage_post_path(post),
            data: {turbo_method: :delete, turbo_confirm: "Delete this post?"} do %>
          <i class="fa-solid fa-trash"></i>
        <% end %>
      </div>
      <%= link_to post_path(post), class:"text-decoration-none text-black" do %>
        <div class="card-post">
          <% if post.photos.attached? %>
            <img src="<%= cl_image_path(post.photos.first.key)%>", class="first-img" >
          <% else %>
            <img src="<%= "https://source.unsplash.com/random/?#{post.title}" %>", class="first-img">
          <% end %>
          <div class="card-post-info">
            <h3 class="mb-2"><%= post.title %></h3>
            <div class="user-info">
              <%= image_tag post.user.avatar, class:"avatar-post me-2" %>
              <p><%= post.user.name %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/mypage/posts/index.html.erb
<div class="container my-3">
  <h3 class="text-center my-4">投稿済みの記事一覧</h3>
  <%= render "postcard" %>
</div>

app/views/mypage/users/_edit-modal.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn modal-btn" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
  編集 ✏️
</button>
<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="staticBackdropLabel">プロフィールを編集</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= simple_form_for(@user) do |f| %>
          <%= f.input :avatar, label:"プロフィール画像", as: :file, input_html:{ class:'form-control bg-white mb-4'} %>
          <%= f.input :name, label:"ニックネーム", input_html:{class:'form-control bg-white'}%>
          <%= f.input :location, label:"居住地", input_html:{class:'form-control bg-white'}%>
          <%= f.input :description, label:"自己紹介", input_html:{class:'form-control bg-white', rows: 3}%>
          <div class="text-center">
            <%= f.submit "保存", class: "btn btn-info text-white col-4" %>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">キャンセル</button>
      </div>
    </div>
  </div>
</div>

app/views/mypage/users/show.html.erb
<div class="container my-3">
  <h3 class="text-center my-4">マイプロフィール</h3>
  <%= render "profile" %>
  <%= render "edit-modal" %>
</div>

app/views/pages/_categories.html.erb
<div>
  <ul class="display-categories">
    <% Post::CATEGORIES.each do |category| %>
      <li><%= link_to category, category_posts_path(category: category) %></li>
    <% end %>
  </ul>
</div>

app/views/pages/_postcard.html.erb
<div class="cards">
  <% @posts.each do |post| %>
    <%= link_to post_path(post), class:"text-decoration-none text-black" do %>
      <div class="card-post">
        <% if post.photos.attached? %>
          <img src="<%= cl_image_path(post.photos.first.key)%>", class="first-img" >
        <% else %>
          <img src="<%= "https://source.unsplash.com/random/?#{post.title}" %>", class="first-img">
        <% end %>
        <div class="card-post-info">
          <h3 class="mb-2"><%= post.title %></h3>
          <div class="category-label">
            <div class="user-info">
              <%= image_tag post.user.avatar, class:"avatar-post me-2" %>
              <p><%= post.user.name %></p>
            </div>
            <p class="label"><%= post.category %></p>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/pages/home.html.erb
<div class="container my-3">
  <%= render "categories" %>
  <%= render "postcard" %>
</div>

app/views/posts/_new-form.html.erb
<div class="row justify-content-center">
  <h4 class="my-3 text-center">新しい記事を投稿 📝</h4>
  <div class="form bg-white col-6 py-5 px-5">
    <%= simple_form_for(@post) do |f| %>
      <%= f.input :title, label:"タイトル", input_html:{class:'form-control bg-white'}%>
      <%= f.input :description, label:"本文", input_html:{class:'form-control bg-white', rows: 3}%>
      <%= f.input :location, label:"場所(都市名)", input_html:{class:'form-control bg-white'}%>
      <%= f.input :category, as: :radio_buttons, label:"カテゴリー", input_html: { class: "tag-selector" },
                  item_wrapper_class: 'tag-item', collection: Post::CATEGORIES%>
      <%= f.input :photos, label:"写真", as: :file, input_html:{ class:'form-control bg-white mb-4', multiple: true } %>
      <div class="d-grid">
        <%= f.submit "投稿", class: "btn btn-info text-white" %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/_post.html.erb
<div class="post-container">
  <% if @post.photos.attached? %>
    <img src="<%= cl_image_path(@post.photos.first.key)%>", class="post-img my-3" >
  <% else %>
    <img src="<%= "https://source.unsplash.com/random/?#{@post.title}" %>", class="post-img my-3">
  <% end %>
  <div>
    <h3 class="mb-2"><%= @post.title %></h3>
    <div class="user-info">
      <%= image_tag @post.user.avatar, class:"avatar-post me-2" %>
      <p><%= @post.user.name %></p>
    </div>
    <p><%= @post.description %></p>
  </div>
</div>

app/views/posts/_writer-profile.html.erb
<div class="col-2 mt-5 sticky-profile">
  <%= link_to posts_path do %>
    <i class="fa-solid fa-backward"></i>
  <% end %>
  <div class="mt-2 post-profile">
    <%= link_to user_path do  %>
      <div class="user-info">
        <%= image_tag @post.user.avatar, class:"avatar-post me-2" %>
        <p><%= @post.user.name %></p>
      </div>
    <% end %>
    <div>
      <p class="writer-location">📍 <%= @post.user.location %></p>
      <p class="writer-description"><%= @post.user.description %></p>
    </div>
  </div>
</div>

app/views/posts/category.html.erb
<div class="container my-3">
  <%= render "pages/postcard" %>
</div>

app/views/posts/index.html.erb
<div class="container my-3">
  <%= render "pages/categories" %>
  <%= render "pages/postcard" %>
</div>

app/views/posts/new.html.erb
<div class="container">
  <%= render "new-form" %>
</div>

app/views/posts/show.html.erb
<div class="container d-flex">
  <%= render "writer-profile" %>
  <%= render "post" %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Globe Tales 2023
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand ms-2" do %>
      <%= image_tag "site-logo.png" %>
    <% end %>
    <%= render "shared/searchbox" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active me-3">
            <a href="#"><i class="fa-regular fa-bell" style="font-size: 22px;"></i></a>
          </li>
          <li class="nav-item dropdown me-3">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag current_user.avatar, class: "avatar", alt: "dropdown menu" %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "自分の投稿", mypage_posts_path, class: "dropdown-item" %>
              <%= link_to "お気に入り", mypage_bookmarks_path, class: "dropdown-item" %>
              <%= link_to "マイページ", mypage_user_path(current_user), class: "dropdown-item" %>
              <hr width="100%" class="text-center">
              <%= link_to "ログアウト", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
          <li class="nav-item">
            <%= link_to "投稿 📝", new_post_path , class:"btn btn-info me-2" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_searchbox.html.erb
<div class="justify-content-center" id="overwrite">
  <div class="form-outline">
    <%= form_with url: posts_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :q,
            params[:q],
            class: "form-control",
            placeholder: "キーワードで検索"
        %>
      <%= button_tag name: "", class: "btn btn-info" do %>
        <i class="fas fa-search"></i>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/_postcard.html.erb
<div class="cards">
  <% @user.posts.each do |post| %>
    <%= link_to post_path(post), class:"text-decoration-none text-black" do %>
      <div class="card-post">
        <% if post.photos.attached? %>
          <img src="<%= cl_image_path(post.photos.first.key)%>", class="first-img" >
        <% else %>
          <img src="<%= "https://source.unsplash.com/random/?#{post.title}" %>", class="first-img">
        <% end %>
        <div class="card-post-info">
          <h3 class="mb-2"><%= post.title %></h3>
          <div class="category-label">
            <div class="user-info">
              <%= image_tag post.user.avatar, class:"avatar-post me-2" %>
              <p><%= post.user.name %></p>
            </div>
            <p class="label"><%= post.category %></p>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/_profile.html.erb
<div class="text-center profile-table">
  <%= image_tag @user.avatar, class:"avatar-profile me-2 my-2" %>
  <table>
    <tr>
      <th>ニックネーム</th>
      <td><%= @user.name %></td>
    </tr>
    <tr>
      <th>居住地</th>
      <td><%= @user.location %></td>
    </tr>
    <tr>
      <th>自己紹介</th>
      <td><%= @user.description %></td>
    </tr>
  </table>
</div>

app/views/users/show.html.erb
<div class="container my-3">
  <h3 class="text-center my-4"><%= @user.name %>さんのプロフィール</h3>
  <%= render "profile" %>
  <h3 class="text-center my-4"><%= @user.name %>さんの投稿一覧</h3>
  <%= render "postcard" %>
</div>